# .woodpecker.yml
when:
  branch: [main, master, dev]

steps:
  main:
    image: ubuntu

    commands:
      - sh worker.sh
      - DIR="$(pwd)" PAGES="pages" gitio branch
      - DIR="$(pwd)" TAG="latest" gitio container

    secrets:
      - SYSTEM_TOKEN
      - SYSTEM_TOKEN_PASSWD
      - OCI_TOKEN
