# .woodpecker.yml
when:
  branch: [main, master, dev]

steps:
  main:
    image: alpine

    commands:
      - sh worker.sh
      - gitio branch GIT_BRANCH:pages
      - gitio container OUTPUT_IMAGE_NAME:gitio:$GIT_BRANCH

    secrets:
      - SYSTEM_TOKEN
      - SYSTEM_TOKEN_PASSWD
      - OCI_TOKEN
