# .woodpecker.yml
when:
  branch: [main, master, dev]

steps:
  main:
    image: ubuntu

    privileged: true
    
    commands:
      - echo "Starting..."
      - export LOCAL_DIR="$(pwd)"
      - sh woodpecker-handler.sh env
      - sh woodpecker-handler.sh codeberg
      - sh woodpecker-container.sh
      - export GIT_EMAIL='gameplayer2019pl@tutamail.com'
      - export GIT_DIR="$(pwd)"
      - export CMD_TYPE='branch'
      - sh woodpecker-handler.sh ssh
      - sh woodpecker-handler.sh
    secrets:
      - SYSTEM_TOKEN
      - OCI_TOKEN
