# .woodpecker.yml
when:
  branch: [main, master, dev]

steps:
  main:
    image: alpine

    commands:
      - sh worker.sh
      - gitio branch GIT_BRANCH:pages
      - export CONTAINER_TAGGING="$(basename "$CI_COMMIT_REF")"
      - if [ "$CONTAINER_TAGGING" = "main" ]; then export CONTAINER_TAGGING="latest"; fi
      - gitio container OUTPUT_IMAGE_NAME:$CI_REPO_NAME:"$CONTAINER_TAGGING"

    secrets:
      - SYSTEM_TOKEN
      - SYSTEM_TOKEN_PASSWD
      - OCI_TOKEN
