name: 'gitio-chimmie'
description: 'An I/O for the Git server communication & builder.'
author: 'Chimmie Firefly'

branding:
  icon: 'activity'
  color: 'orange'

inputs:
  type:
    description: 'Runtime I/O type.'
    required: false
    default: 'checkout'
  cmd:
    description: 'Commands for the I/O type.'
    required: false
    default: ''
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'GitHub Repository Name'
    required: false
    default: ${{ github.repository }}
  ref:
    description: 'GitHub Ref'
    required: false
    default: ${{ github.ref }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --build-arg CMD_TYPE=${{ inputs.type }}
    - --build-arg CMD=${{ inputs.cmd }}
    - --build-arg GITHUB_TOKEN=${{ inputs.token }}
    - --build-arg GITHUB_REPO=${{ inputs.repository }}
    - --build-arg GITHUB_REF=${{ inputs.ref }}
